### PR TITLE
Mike's edits preparing us to publish Cleartext JWS and JWE -00

### PR DESCRIPTION
**Pull request by selfissued**

### CODE REVIEW

**Comment by cyberphone** [comment]
Thank you very much for the thorough review and the considerable updates of prose and details!
I look forward to the submission of these two specifications.

You will do that?  Better ask so we don't fail on such a pitiful detail :-)

**Comment by selfissued** [comment]
You're welcome.  I wanted this to be solid, because we only get once chance to make a first impression.  I take it that you approve of merging these edits then, after Samuel looks at them.

I think Samuel should be the one to submit the specs, since they're "draft-erdtman-" specs.

**Comment by cyberphone** [comment]
I indeed approve these edits and assume Samuel does that as well.

Samuel, you are apparently also the submitter!

**Comment by erdtman** [comment]
Looks great to me!

**Pull request merged**
